from flask import send_file
from flask_restful import Resource
from abc import abstractmethod


class MultiBeam(Resource):
    """
    The multi-beam parent class. The multi-beam is a collection of beams generated by the backend
    """

    @abstractmethod
    def get(self, observation, data_set):
        pass


class RawMultiBeam(MultiBeam):
    """
    The multi-beam without filtering
    """

    def get(self, observation, data_set):
        # generate raw beam image
        # send raw image to client
        pass


class FilteredMultiBeam(MultiBeam):
    """
    The multi-beam after filtering was applied
    """

    def get(self, observation, data_set):
        # generate filtered beam image
        # send filtered image to client
        pass
